### PR TITLE
Odoc

### PR DESCRIPTION
**Pull request by mlms13**
I have no idea if GitHub Actions will do anything useful with this. Ideally it should create a `gh-pages` branch. If that works, I'll switch the action `.yml` to only run when a new tag is pushed, but I set it to run on PR for testing purposes.

TODO:

- [x] Did docs generate?
- [x] Does CSS exist?
- [x] Pull in a highlight.js theme as part of the GitHub action
- [x] Change doc comment formatting to match [the expected style](http://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html#s%3Aocamldoc-comments), possibly using [lwt](https://github.com/ocsigen/lwt/blob/master/src/core/lwt.mli) as an example
- [x] Change publishing of website from docs folder to `gh-pages` branch (which should automatically get the master docs folder copied in
- [x] Check docs for broken links
  - [x] Sidebar link to API goes to the wrong place
- [x] Module comments [incorrectly get attached to the first expression](https://github.com/facebook/reason/issues/2419)
- [x] Update CONTRIBUTING guidelines to make sure docs are written consistently going forward
- [ ] Change action trigger to "push tags" (instead of triggering on pr)

### CODE REVIEW

**Comment by mlms13** [comment]
Oh boy, looks like a sloppy copy-and-paste, but the ~15 minutes needed to actually test the action is going to make iteration painful.

**Comment by mlms13** [comment]
There are some very rough edges, but [here's some proof](https://reazen.github.io/relude/api/Relude_Float/) that things are happening.

I'm pushing a change now that may fix the missing CSS, but I'm not going to wait around for it to finish. Tomorrow, I'll make sure that's working, and I'll try to clean up our comment style to make it format nicer with odoc.

**Comment by mlms13** [comment]
As I've been translating existing comments to odoc syntax, I've run into several gotchas. I'm going to take notes here because I have nowhere better to put them for now:

- Either RLS or vscode _really_ wants to put a leading `*` at the beginning of each comment line, but don't let it! `odoc` preserves that `*` in the generated output.
- Module-level comments are determined to attach themselves to the first expression in the file if you use `/** ... */` syntax, so use `[@ocaml.txt {| ... |}]` instead
- Comment headings (e.g. `{1 Title}` don't seem to work at all in `/** */` comments, so again `@ocaml.text` to the rescue
- You're supposed to be able to cross-reference to other modules/types/values using `{!Module_Name}` but `{!Relude_Globals}` generates no link and `{!Relude.Globals}` generates a broken link so I'm just using the full link syntax: `{{: ../Relude_Globals} [Relude.Globals]}`

**Comment by andywhite37** [comment]
What an amazing system this is!

**Comment by mlms13** [comment]
If this build completes successfully, I think I've made the changes I plan on making, and the actual docs site is ready for review.

What this PR does:

- Generate docs site with odoc and publish to `gh-pages`
- Change our doc style to be compatible with odoc
- Document guidelines so that it's easier for people to add consistent docs in the future

What this doesn't do (but would be good for a future effort):

- Add new docs to previously undocumented functions
- Make existing doc style consistent (I did this for a few modules, but quickly got overwhelmed)
  - Not all docs wrap at column 80
  - Not all docs use full sentences
  - Not all docs include example usage that reflects real-world scenarios

And finally, in case anyone else ever needs to migrate from markdown-formatted docs to odoc's format, here are some regular expressions that helped out (Vim-style substitution using JS-flavored regex... it's weird, but it works in vscode with the Vim plugin):

1. Clean leading stars: `:%s/^\s\*(\s|$)//gc`
2. Un-indent closing comment: `:%s/^\s\*\//*\//gc`
3. Replace code block triple backtick:
`:%s/^(\s+?)```(re|reason|reasonml)?([\s\S]+?)(\s+?)```/{[$1]}/gc`
4. Replace single backtick code: `:%s/`(.+?)`/[$1]/gc`

Bullet 3 doesn't actually work... for the life of me, I couldn't get multi-line capture groups working, but the _idea_ seems right.

**Comment by mlms13** [comment]
I switched the release script to only generate the site when a new tag is pushed (we'll have to make sure that's actually working at some point).

Otherwise, I feel pretty good about merging this. It's very possible that there are formatting errors I missed, or typos in the docs, but at least now they'll be exposed to a wider audience, and we can fix things as we go.

**Comment by johnhaley81** [comment]
🎉

**Pull request merged**
