### PR TITLE
Add `Cancel` to IO

### PR DESCRIPTION
**Pull request by johnhaley81**
Some exploratory code for issue https://github.com/reazen/relude/issues/171

### CODE REVIEW

**Comment by andywhite37** [comment]
@johnhaley81 - I checked out the code last night, thanks for starting the conversation and work on this!

I think we should absolutely have `debounce` and `throttle` in relude - so I want to see this through.  For this particular implementation, I think the key to all this is the ability to cancel the `IO`, and that is a handy thing to support on its own.

Just to make sure I understand the approach - let me list out my observations, and let me know if you agree or disagree with any of these:

1. There is a new `IO` constructor `Cancel` which basically acts as a no-op/no-continue type of operation in an IO chain
    - e.g. in the `unsafeRunAsync` function, when a `Cancel` is reached, it basically just stops the processing, and never invokes the `done` callback
    - other operations just kind of dead-end on the `Cancel` value - like maps/flip/etc.
1. The `cancelIO` function appends a `Cancel` value at the end of the `IO` chain via `flatMap`
1. When an `IO` is run, it will still run the effects up to the point it reaches a `Cancel`, it just basically stops when it reaches the `Cancel` and never invokes the done callback

Item 3 above is my main concern with this approach, because I think it might confuse people that calling `cancelIO` doesn't actually stop the effects leading up to the `Cancel` from being run - it just suppresses the `unsafeRunAsync` callback - is that correct?  I looked at some other libs and `Promise` implementations out there, and a common thread seems to be a `Canceler` function that is kind of baked into the `Promise` or returned with it - I'm wondering if we should explore that line, and see if we can make a way to actually cancel an in-flight `IO`.

`setTimeout` creates a nice simple testbed for this idea, but I haven't fully thought it through or actually figured out if this could work or not.  Below was just an initial idea:

```reason
module Result = {
  type t('a, 'e) = | Ok('a) | Error('e);
};

module IO = {
  type canceler = unit => unit;

  // Simplified IO type
  // Async lets you return an optional canceler function - not sure if this would work - haven't gotten far enough to find out
  type t('a, 'e) =
    | Pure('a) : t('a, 'e)
    | Throw('e) : t('a, 'e)
    | Async((Result.t('a, 'e) => unit) => option(canceler)) : t('a, 'e);
  
  let pure = a => Pure(a);

  let throw = e => Throw(e);

  let async = onDone => Async(onDone);
   
  // TODO: add some more things here
};

let testTimeoutIO = (getValue: unit => 'a): t('a, 'e) => {
  async(onDone => {
    let canceler = ref(() => ());
    
    let timeoutId = Js.Global.setTimeout(() => {
      onDone(Ok(getValue()));
    }, 2000)
          
    // Return the canceller function
    Some(() => Js.Global.clearTimeout(timeoutId));
  });
};
```

Another passing thought I had on this was to not modify the `IO` type at all, and just create separate functions that use a callback-based approach to debounce and throttle.  (I also have not throught this fully through).  The driver for this is the observation that an `IO` value is immutable, and doesn't actually do anything until you run it (as you know), so I was thinking that a debounce function could basically work similarly to yours and update a mutable ref to the "current" IO that should be run, and when the timer expires, it just runs that IO, and invokes a user-supplied callback when that last IO completes.  I'm not sure if this makes any sense, or if it would work, but do you have any thoughts on that?

```reasonml
// pseudo/incomplete code
let debounce = (makeIO: unit => IO.t('a, 'e), onDone: Belt.Result.t('a, 'e) => unit) => {
  let currentIO = ref(makeIO());
  // do timer stuff and update IO
  // When timer expires, run currentIO and invoke onDone
};
```

**Comment by andywhite37** [comment]
BTW - we made the decision to use the one `l` version of `canceler`/`cancelable`/etc. in `relude-reason-react`, but my brain really wants to use two `ll`s, so forgive me if I'm inconsistent, but we should try to use the one `l` version if we can.

**Comment by johnhaley81** [comment]
I think I might have found a simple solution to #3. Let me know what you think 😄

**Comment by johnhaley81** [comment]
I meant to add some more context with my approach but life got in the way :)

So I'd like to comment on your above observations:

> There is a new IO constructor Cancel which basically acts as a no-op/no-continue type of operation in an IO chain

Yep! Basically as soon as `unsafeRunAsync` hits a `Cancel` everything just short circuits out and nothing gets called including the final `onDone` callback.

> The cancelIO function appends a Cancel value at the end of the IO chain via flatMap - IO is immutable, so we can't currently cause the cancellation of anything leading up to the appended Cancel 

I thought about this a bit and I did a small change to how we construct the IO. Now the function `cancelIO` prepends the cancel to the returned IO which effectively nullifies everything that the IO is doing. Even though it's immutable we can stuff change what's happening before the passed in IO so we actually can cancel an already constructed IO. Anything with the reference to the original IO however can still run it just fine since it is immutable.

This assumes though that the IO is correctly constructed and is referentially transparent/lazy/etc... otherwise there's not much we can do.

> When an IO is run, it will still run the effects up to the point it reaches a Cancel, it just basically stops when it reaches the Cancel and never invokes the done callback

With the recent change this is no longer true. The IO that is retuned from the `cancelIO` function will not have anything in it execute. The original IO can still be run and further composed with however.

**Comment by andywhite37** [comment]
I'm going to check out your branch tonight and play around with the `debounce` and `throttle` functions just for my own understanding of the problem and approach.  I think the thing I'm weighing is whether we need the `Cancel` constructor at all for these to work the way they work.  I think I understand what you are trying to achieve, but I want to just poke around for a little.

The reason I say this is b/c an `IO` doesn't really need to be cancelled in this way, if it hasn't been run yet.  If you construct an `IO`, it doesn't do anything until you run it, and if you do run it, this `Cancel` mechanism I don't think actually does anything to that in-flight `IO`.  Also with the `cancelIO` function putting the `Cancel` at the beginning of the chain rather than the end, is basically the same as just returning a static `Cancel` outright, and neither actually affect the input `IO` if it has already been run.  And if it hasn't been run yet, there's no need to cancel it - you can just not run it (that's my theory at least).

I'm wondering if this style of `debounce` and `throttle` can just be implmeneted with a `ref` to an `IO` or (lazy `IO`) which basically just returns the "last" `a => IO` that should be run at the end of the debouncing/throttling, rather than making `IO`s that haven't been started as canceled.  I do like the idea of having a function that returns a debounced/throttled "lazy" `IO` value makes sense.

**Comment by andywhite37** [comment]
I didn't get a chance to look at it last night, and I probably won't be able to tonight either, but hopefully this week.  Sorry for the delay, I've had some things going on in the evenings these past few weeks.

**Comment by andywhite37** [comment]
@johnhaley81 - sorry for continued delays on this - I've had some things in the evenings and weekends and haven't been able to dedicate the time I want to dedicate to this.  I have been looking at your PR, and other debounce/throttle implementations in the wild, and am still considering how to move forward on this.

I think I'm leaning towards not wanting to do the `Cancel` constructor in `IO` itself, as I think it creates a confusing expectation given the immutability of an `IO` value, the fact that the `Cancel` doesn't actually cancel a running `IO`, and the fact that there's not really a need to cancel an `IO` that hasn't been started, as there's nothing to cancel.  I do think there is a need for cancelling an `IO`, but I think I'd like to tackle that problem in terms of cancelling a running `IO`, maybe via a cancel callback or something.  I imagine the cancel function would be returned by `unsafeRunAsync` - like a handle to cancel a running IO in whatever state it's in, but I don't know exactly what that will look like.

I'm currently considering/playing with a plain-old function-based `debounce`/`throttle` (using a `unit => unit` function, as you mentioned).  I'd like to see how this might fit into a Relude-based ReasonReact app where you might want to debounce some event like `keyup` or window `resize`, and emit an `IO` at the end of a debounce/throttle cycle.  Sort of like the `UpdateWithIO` stuff we have in the `ReludeReact.Reducer` hook - something that is `IO`-based but tries to hide the `unsafeRunAsync` from the end users in a convenient way.

**Comment by johnhaley81** [comment]
@andywhite37 I added another test case to show how you can use this to cancel an in-flight `IO.` 

Having the `Cancel` constructor does force the logic of cancelling to be inside of the `IO` monad however but that does maintain the the idea of keeping the logic of the `IO` composable AFAIK since once you hit the `unsafeRunAsync` method all bets are off.

**Comment by andywhite37** [comment]
Thanks @johnhaley81 - yeah, I get what `Cancel` is doing in the IO function chain - it basically just puts a roadblock in the IO chain at the point it's inserted.  `cancelIO` appends it at the beginning (which is essentially the same as just returning `Cancel` by itself, but maybe you can't do that b/c the types then don't line up?)  If you insert it mid-way, when you run the `IO` it will run the effects up to that point, then stop and never invoke the final callback of `unsafeRunAsync`.

Just to state my thoughts, you can achieve the same thing as `cancelIO` by just not running an `IO`, and you can achieve the same thing as inserting a `Cancel` mid-way in an `IO` by just creating an `IO` with effects that don't go beyond where you were wanting to cancel it.

The thing I'm struggling with is that you don't really need `Cancel`, other than to implement the mutable IO manipulation in `debounceIO` to satisfy the current type signature.  I.e. deciding after the `IO` delay whether to continue the IO or cancel it via an impure/mutable condition in the `flatMap` and returning an actual `IO` value at that point, which forks the flow based on an impure check.  I get what you're doing in `debounceIO`, but I can't decide if that's the direction I want to go - the `IO`s produced by debounceIO are no longer referentially transparent, because they have a impure condition injected in them.  That's not the end of the world if it only affects `debounceIO`, but I'm not convinced that that justifies needing the `Cancel` constructor.

Would it be possible to implement `debounceIO` in the way you have it where the returned function is `'r => IO.t(option('a), 'e)` rather than `'r => IO.t('a, 'e)` - so that when you call the function and it gets debounced, you can fork the flow to return `IO.pure(None)` rather than `Cancel`?  I think if that's possible, we wouldn't need the `Cancel` (not 100% sure)?  I could live with `debounceIO` producing impure IOs if doing so was kind of isolated to that one function.

**Comment by johnhaley81** [comment]
Definitely hear your thoughts and honestly agree with what you're thinking. The things that I was trying to solve were to get the types to line up, and to have a way to stop something after the `unsafeRunAsync` function was called. `Cancel` should probably have been renamed to `Halt` or something since that's closer to what it's doing. 

As far as not needing something like this, I whipped it up because the original solution I had just had a `IO.Async` that threw out the `onDone` callback which achieved what I was trying to do but felt hacky/wrong. So having a `Cancel` constructor isn't _really_ needed but it felt more explicit instead of the `IO.Async` hack.

I do like that `option` idea. I'll try to get that going.

**Comment by andywhite37** [comment]
Sweet - I see your latest commit, and if this works for you, I'm totally down to merge this.  Thanks for working through this with me, it was a mind-bender!

**Comment by johnhaley81** [comment]
I'm still not 100% happy with it but honestly I'm really struggling with making a referentially transparent debounce. I think this is at least a good next step so I'm 👍 on it.

**Comment by andywhite37** [comment]
Released in 0.31.0

**Pull request merged**
