### PR TITLE
Initial RIO Monad

### PR DESCRIPTION
**Pull request by RawToast**
Initial attempt for #128

### CODE REVIEW

**Comment by RawToast** [comment]
Again I'd like to go through this with tests. It looks okay, but it could all be useless 😸

**Comment by andywhite37** [comment]
Hey @RawToast - sorry I didn't reply over the weekend.  I'll take a look tonight!  Thanks again for working on this

**Comment by RawToast** [comment]
No problem :) I'll see what tests I can add today/tomorrow.

**Comment by andywhite37** [comment]
This looks good to me, test failures are known issues in #184, so I'll merge.

We can iterate on it more going forward, but this looks like what I was envisioning to start with!

**Pull request merged**
