### PR TITLE
Parallel IO apply and some other refactoring (first draft)

### PR DESCRIPTION
**Pull request by andywhite37**
I'm going to try this out in our production app a little bit before I merge & release.

### CODE REVIEW

**Comment by andywhite37** [comment]
Well, initial tests seem to be very successful!  We have a few places in our app that were using the `List.IO.traverse` (which uses IO.apply under the hood as a traversable), and some `IO.mapN`, and they seem to now run in parallel rather than serial.

I'm going to go ahead and merge this to release it to the wild and get more feedback.

**Comment by johnhaley81** [comment]
🎉

I'm going to pull this in and see how it goes!

**Comment by andywhite37** [comment]
Cool - thanks!  Thanks too for the idea to just add the `Apply` constructor - that seemed to work nicely, like one might expect!  I'm still debating removing the `Suspend` and `SuspendIO` constructors to simplify everything, but I opted to leave them in for now, as I figured it would be easier to write all the code then remove parts that we don't want after the fact.

**Comment by mlms13** [comment]
I'm glad the "What was I thinking?" commit can forever be part of our main-line history. :grin:

**Pull request merged**
